version: '3'

services:
  app:
    build: .
    image: desafio-02-daily-diet-node-2023:latest
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    command: npm run dev

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: daily-diet
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: